import type { CaseDef } from "../../game/cases";

export const cityhallCase: CaseDef = {
  id: "cityhall",
  building: "City Hall",
  sprite: "cityhall",
  title: "The Budget That Doubled",
  tag: "CASE 03",
  brief: "A council candidate says spending exploded. The ledger says something quieter.",
  article: {
    outlet: "THE ROSEWOOD LEDGER",
    headline: "Council Spending Draws Fire Ahead Of Vote",
    byline: "by M. Alvarez",
    dateline: "CITY HALL — THURSDAY",
    body: [
      "City Hall's operating budget ~h1{rose from $8.2M to $9.1M over four years}, according to the annual finance reports posted on the city portal.",
      "Candidate Weller told a rally on Wednesday the budget had ~h2{doubled in a single year}, a figure his campaign has repeated in three mailers.",
      "~h3{Most of the increase went to the water main replacement programme}, the finance office said, which was approved by public referendum in 2022.",
      "Weller's campaign ~h4{declined to provide the source of its figure} when asked twice by this paper.",
    ],
  },
  social: {
    app: "CHATTR",
    handle: "@weller4rosewood",
    display: "Weller For Rosewood",
    avatar: "bust2",
    time: "18h",
    body: "City Hall's budget ~h5{is up 11% since 2021} — and they want more. ~h6{Not one cent of it reached your street.} Vote them out.",
    likes: "780",
    reposts: "204",
    replies: "533",
  },
  quote: {
    speaker: "Priya Nandakumar",
    role: "City Finance Officer",
    avatar: "bust1",
    outletNote: "On the record, City Hall, Thurs 11am",
    body: '"The four-year increase is eleven percent. ~h7{Roughly seventy percent of that is the water main works voters approved.}"',
  },
  hotspots: [
    {
      id: "h1",
      text: "rose from $8.2M to $9.1M over four years",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "cherry", "exaggerate"],
      note: "Published in the annual finance reports. Anyone can pull them.",
    },
    {
      id: "h2",
      text: "doubled in a single year",
      source: "article",
      misleading: true,
      correctReason: "exaggerate",
      chips: ["exaggerate", "records", "context"],
      note: "Eleven percent over four years is not doubling in one. The paper quoted the claim — your job was to catch it.",
    },
    {
      id: "h3",
      text: "Most of the increase went to the water main replacement programme",
      source: "article",
      misleading: false,
      correctReason: "confirmed",
      chips: ["confirmed", "nosource", "fabricated"],
      note: "The finance office said it and the referendum record supports it.",
    },
    {
      id: "h4",
      text: "declined to provide the source of its figure",
      source: "article",
      misleading: false,
      correctReason: "onrecord",
      chips: ["onrecord", "exaggerate", "cherry"],
      note: "The paper documented its own attempts to verify. That's the job done right.",
    },
    {
      id: "h5",
      text: "is up 11% since 2021",
      source: "social",
      misleading: false,
      correctReason: "records",
      chips: ["records", "cherry", "fabricated"],
      note: "Accurate — even a campaign account gets one right sometimes. Don't flag a claim for who said it.",
    },
    {
      id: "h6",
      text: "Not one cent of it reached your street.",
      source: "social",
      misleading: true,
      correctReason: "context",
      chips: ["context", "nosource", "records"],
      note: "Seventy percent went to water mains under those same streets. Omission does the lying here.",
    },
    {
      id: "h7",
      text: "Roughly seventy percent of that is the water main works voters approved.",
      source: "quote",
      misleading: false,
      correctReason: "onrecord",
      chips: ["onrecord", "cherry", "context"],
      note: "Named officer, on record, consistent with the published ledger.",
    },
  ],
};
