import type { CaseDef } from "../../game/cases";

/* NOTE: this case runs as a "stage" (see CASE_GAMES + school/Game.tsx), so
   the article/social/quote/hotspots content below is never rendered — stage
   games only use building/sprite/title/tag/brief. Left in place rather than
   deleted in case a future Investigation-style case wants to reuse it. */
export const schoolCase: CaseDef = {
  id: "school",
  building: "Rosewood High",
  sprite: "school",
  spriteScale: 3,
  title: "Written By Nobody",
  tag: "CASE 07",
  brief: "The group chat is full of AI-made stuff this week. Can you tell what's real?",
  article: {
    outlet: "THE ROSEWOOD LEDGER",
    headline: "District Reviews Dip In Ninth Grade Reading Scores",
    byline: "by M. Alvarez",
    dateline: "ROSEWOOD HIGH — WEDNESDAY",
    body: [
      "Ninth grade reading scores ~h1{fell four points against last year's cohort}, per the district's published assessment summary.",
      "The summary also notes ~h2{the cohort grew by 140 students after two schools merged in August}.",
      "~h3{Teachers have simply given up on the students.} Not one teacher is quoted in support of that line.",
      "Twelfth grade scores ~h4{rose two points in the same assessment}.",
    ],
  },
  social: {
    app: "CHATTR",
    handle: "@parents_rw",
    display: "Rosewood Parents",
    avatar: "bust2",
    time: "9h",
    body: "Reading scores ~h5{collapsed district-wide}. ~h6{Ninth grade is down four points.} What are we paying for?",
    likes: "1.9K",
    reposts: "508",
    replies: "377",
  },
  quote: {
    speaker: "Dr. Amina Roche",
    role: "District Assessment Lead",
    avatar: "bust1",
    outletNote: "On the record, district office, Wed 3pm",
    body: '"~h7{Ninth grade is down four; twelfth is up two, and the cohort changed size mid-year.} One number is not a district."',
  },
  hotspots: [
    {
      id: "h1",
      text: "fell four points against last year's cohort",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "cherry", "exaggerate"],
      note: "Published, specific, and correctly bounded to one grade.",
    },
    {
      id: "h2",
      text: "the cohort grew by 140 students after two schools merged in August",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "nosource", "fabricated"],
      note: "The context that makes the four-point dip interpretable.",
    },
    {
      id: "h3",
      text: "Teachers have simply given up on the students.",
      source: "article",
      misleading: true,
      correctReason: "nosource",
      chips: ["nosource", "cherry", "records"],
      note: "An accusation with nobody behind it. The article all but admits it.",
    },
    {
      id: "h4",
      text: "rose two points in the same assessment",
      source: "article",
      misleading: false,
      correctReason: "confirmed",
      chips: ["confirmed", "exaggerate", "context"],
      note: "Same document, confirmed by the assessment lead.",
    },
    {
      id: "h5",
      text: "collapsed district-wide",
      source: "social",
      misleading: true,
      correctReason: "context",
      chips: ["context", "records", "onrecord"],
      note: "One grade down, another up. 'District-wide' is doing work the data won't do.",
    },
    {
      id: "h6",
      text: "Ninth grade is down four points.",
      source: "social",
      misleading: false,
      correctReason: "records",
      chips: ["records", "cherry", "fabricated"],
      note: "Correct, and correctly scoped. Flag the frame, not the fact.",
    },
    {
      id: "h7",
      text: "Ninth grade is down four; twelfth is up two, and the cohort changed size mid-year.",
      source: "quote",
      misleading: false,
      correctReason: "onrecord",
      chips: ["onrecord", "cherry", "context"],
      note: "Named expert, full picture, on record. That's how you close a case.",
    },
  ],
};