import type { CaseDef } from "../../game/cases";

export const policeCase: CaseDef = {
  id: "police",
  building: "5th Precinct",
  sprite: "police",
  title: "Crime Wave, Allegedly",
  tag: "CASE 06",
  brief: "Two true numbers, arranged to tell a lie.",
  article: {
    outlet: "THE ROSEWOOD LEDGER",
    headline: "Precinct Reports Rise In Reported Thefts",
    byline: "by K. Ford",
    dateline: "5TH PRECINCT — FRIDAY",
    body: [
      "Reported thefts in the precinct ~h1{rose 22% between January and March}, according to the quarterly crime data release.",
      "The same release notes ~h2{a new online reporting portal opened in January}, which the precinct says increased the share of incidents that get reported at all.",
      "~h3{Rosewood is now the most dangerous district in the state.} The state ranking places it 44th of 61 for violent crime.",
      "Violent crime in the precinct ~h4{fell 6% over the same quarter}, the release shows.",
    ],
  },
  social: {
    app: "CHATTR",
    handle: "@rosewood_watch",
    display: "Rosewood Watch",
    avatar: "bust1",
    time: "4h",
    body: "Theft up 22% in ONE QUARTER. ~h5{Nobody is safe walking home.} ~h6{They opened a reporting portal in January} but sure, blame the paperwork.",
    likes: "3.4K",
    reposts: "1.1K",
    replies: "612",
  },
  quote: {
    speaker: "Capt. Del Moreno",
    role: "5th Precinct",
    avatar: "bust2",
    outletNote: "On the record, precinct steps, Fri 2pm",
    body: '"Reports went up. ~h7{We can\'t yet separate more crime from more reporting.} Violent crime is down six percent."',
  },
  hotspots: [
    {
      id: "h1",
      text: "rose 22% between January and March",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "cherry", "fabricated"],
      note: "Straight from the quarterly release. The number is fine; watch what gets built on it.",
    },
    {
      id: "h2",
      text: "a new online reporting portal opened in January",
      source: "article",
      misleading: false,
      correctReason: "confirmed",
      chips: ["confirmed", "context", "nosource"],
      note: "The context that keeps the 22% honest.",
    },
    {
      id: "h3",
      text: "Rosewood is now the most dangerous district in the state.",
      source: "article",
      misleading: true,
      correctReason: "exaggerate",
      chips: ["exaggerate", "records", "onrecord"],
      note: "44th of 61. The sentence contradicts the sentence after it.",
    },
    {
      id: "h4",
      text: "fell 6% over the same quarter",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "cherry", "fabricated"],
      note: "In the release, and repeated on record by the captain.",
    },
    {
      id: "h5",
      text: "Nobody is safe walking home.",
      source: "social",
      misleading: true,
      correctReason: "exaggerate",
      chips: ["exaggerate", "nosource", "records"],
      note: "Violent crime fell six percent. Fear isn't a finding.",
    },
    {
      id: "h6",
      text: "They opened a reporting portal in January",
      source: "social",
      misleading: false,
      correctReason: "records",
      chips: ["records", "fabricated", "cherry"],
      note: "True — they just refuse to let it mean anything.",
    },
    {
      id: "h7",
      text: "We can't yet separate more crime from more reporting.",
      source: "quote",
      misleading: false,
      correctReason: "onrecord",
      chips: ["onrecord", "context", "exaggerate"],
      note: "An official admitting uncertainty on the record. Rarer than it should be.",
    },
  ],
};
