import type { CaseDef } from "../../game/cases";

export const marketCase: CaseDef = {
  id: "market",
  building: "Fourth St. Market",
  sprite: "market",
  spriteScale: 3,
  title: "Six Dollar Tomatoes",
  tag: "CASE 04",
  brief: "A price outrage story built on one very expensive stall.",
  article: {
    outlet: "THE ROSEWOOD LEDGER",
    headline: "Market Prices Spark Complaints From Shoppers",
    byline: "by K. Ford",
    dateline: "FOURTH STREET — SATURDAY",
    body: [
      "Tomatoes at the Fourth Street market ~h1{sold for as much as $6 a pound at one specialty stall} this weekend, a price several shoppers called steep.",
      "The market's own survey lists ~h2{an average tomato price of $2.40 a pound across its eleven produce vendors}.",
      "~h3{Prices at the market have skyrocketed beyond every shop in the county.} Two nearby grocers listed tomatoes at $2.10 and $2.75 the same day.",
      "Market manager Ines Toya ~h4{said the specialty stall grows a heirloom variety in small volume}, which she said explains the gap.",
    ],
  },
  social: {
    app: "CHATTR",
    handle: "@rosewood_watch",
    display: "Rosewood Watch",
    avatar: "bust1",
    time: "6h",
    body: "$6 TOMATOES. ~h5{This is what the market charges now.} My neighbour said ~h6{three stalls have already closed because nobody can afford it}.",
    likes: "2.2K",
    reposts: "641",
    replies: "419",
  },
  quote: {
    speaker: "Ines Toya",
    role: "Market Manager",
    avatar: "bust2",
    outletNote: "On the record, market office, Sat 9am",
    body: '"One stall sells heirlooms at six dollars. ~h7{The average across our vendors is two dollars forty.} Nobody has closed this season."',
  },
  hotspots: [
    {
      id: "h1",
      text: "sold for as much as $6 a pound at one specialty stall",
      source: "article",
      misleading: false,
      correctReason: "confirmed",
      chips: ["confirmed", "cherry", "exaggerate"],
      note: "Precisely scoped: 'as much as', 'one stall'. Precision is the tell of an honest sentence.",
    },
    {
      id: "h2",
      text: "an average tomato price of $2.40 a pound across its eleven produce vendors",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "nosource", "context"],
      note: "The market's own survey, and the manager repeats the number on record.",
    },
    {
      id: "h3",
      text: "Prices at the market have skyrocketed beyond every shop in the county.",
      source: "article",
      misleading: true,
      correctReason: "exaggerate",
      chips: ["exaggerate", "records", "onrecord"],
      note: "'Every shop in the county' — and the very next sentence lists two cheaper ones. Read on before you believe.",
    },
    {
      id: "h4",
      text: "said the specialty stall grows a heirloom variety in small volume",
      source: "article",
      misleading: false,
      correctReason: "onrecord",
      chips: ["onrecord", "fabricated", "nosource"],
      note: "Attributed to a named manager who confirmed it to us directly.",
    },
    {
      id: "h5",
      text: "This is what the market charges now.",
      source: "social",
      misleading: true,
      correctReason: "cherry",
      chips: ["cherry", "records", "confirmed"],
      note: "One outlier stall stretched over eleven vendors. The number is real; the framing isn't.",
    },
    {
      id: "h6",
      text: "three stalls have already closed because nobody can afford it",
      source: "social",
      misleading: true,
      correctReason: "nosource",
      chips: ["nosource", "context", "records"],
      note: "'My neighbour said.' The manager says nobody closed. Hearsay is not a source.",
    },
    {
      id: "h7",
      text: "The average across our vendors is two dollars forty.",
      source: "quote",
      misleading: false,
      correctReason: "records",
      chips: ["records", "cherry", "exaggerate"],
      note: "Matches the market's filed survey line for line.",
    },
  ],
};
