import type { CaseDef } from "../../game/cases";

/* Stage 1 — the onboarding stage. The drills are the gameplay; this dossier is
   the same three-source file every other case carries, so the post office can
   turn up in a Beat the Clock run and read like any other Rosewood story. */

export const postofficeCase: CaseDef = {
  id: "postoffice",
  building: "Rosewood Post Office",
  sprite: "postoffice",
  title: "The Letter That Wasn't",
  tag: "CASE 01",
  brief: "A parcel notice, a login page, and four hundred pounds gone.",
  article: {
    outlet: "THE ROSEWOOD LEDGER",
    headline: "Residents Report Fake Parcel Notices",
    byline: "by T. Okafor",
    dateline: "POST OFFICE ROAD — MONDAY",
    body: [
      "~h1{Eleven residents have reported a text claiming a parcel is held pending a small fee}, according to the post office's own logged complaints.",
      "The link in the message points to ~h2{rosewood-post.delivery-verify.co, which is not a Royal Mail or Rosewood Post address}.",
      "~h3{Every household in Rosewood has been targeted.} No count of that kind exists anywhere in the complaint log.",
      "Postmaster Ade Bello notes that ~h4{the counter never asks for card details by text message}.",
    ],
  },
  social: {
    app: "CHATTR",
    handle: "@rosewood_now",
    display: "Rosewood Now",
    avatar: "bust2",
    time: "3h",
    body: "PSA: ~h5{the post office website has been hacked} — do NOT log in. ~h6{Officials confirmed the link in the text is not theirs.}",
    likes: "2.4K",
    reposts: "918",
    replies: "402",
  },
  quote: {
    speaker: "Ade Bello",
    role: "Postmaster, Rosewood Post Office",
    avatar: "bust1",
    outletNote: "On the record, front counter, Mon 11am",
    body: '"~h7{Our site was never breached. Someone registered a lookalike domain and sent texts to numbers they bought.} Read the address bar before you read the message."',
  },
  hotspots: [
    {
      id: "h1",
      text: "Eleven residents have reported a text claiming a parcel is held pending a small fee",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "nosource", "exaggerate"],
      note: "A counted figure with a log behind it. That is what a number should look like.",
    },
    {
      id: "h2",
      text: "rosewood-post.delivery-verify.co, which is not a Royal Mail or Rosewood Post address",
      source: "article",
      misleading: false,
      correctReason: "confirmed",
      chips: ["confirmed", "fabricated", "context"],
      note: "The domain is the evidence. Everything before the first slash is the only part that cannot be faked.",
    },
    {
      id: "h3",
      text: "Every household in Rosewood has been targeted.",
      source: "article",
      misleading: true,
      correctReason: "exaggerate",
      chips: ["exaggerate", "records", "onrecord"],
      altReasons: ["nosource"],
      note: "Eleven complaints became every household somewhere between the counter and the copy desk.",
    },
    {
      id: "h4",
      text: "the counter never asks for card details by text message",
      source: "article",
      misleading: false,
      correctReason: "onrecord",
      chips: ["onrecord", "unverified", "cherry"],
      note: "Named official, on the record, and checkable in one phone call.",
    },
    {
      id: "h5",
      text: "the post office website has been hacked",
      source: "social",
      misleading: true,
      correctReason: "fabricated",
      chips: ["fabricated", "records", "confirmed"],
      altReasons: ["unverified"],
      note: "A lookalike domain is not a breach. The quote card says so in plain words.",
    },
    {
      id: "h6",
      text: "Officials confirmed the link in the text is not theirs.",
      source: "social",
      misleading: false,
      correctReason: "confirmed",
      chips: ["confirmed", "nosource", "attribution"],
      note: "The one line in the post that survives a check against the record.",
    },
    {
      id: "h7",
      text: "Our site was never breached. Someone registered a lookalike domain and sent texts to numbers they bought.",
      source: "quote",
      misleading: false,
      correctReason: "onrecord",
      chips: ["onrecord", "conflict", "unverified"],
      note: "Named, on the record, and specific enough to be wrong in public if it were.",
    },
  ],
};
