import type { CaseDef } from "../../game/cases";

export const newsofficeCase: CaseDef = {
  id: "newsoffice",
  building: "The Ledger Office",
  sprite: "newsoffice",
  title: "The Correction Nobody Ran",
  tag: "CASE 05",
  brief: "This time the story under the glass is your own paper's.",
  article: {
    outlet: "THE ROSEWOOD LEDGER",
    headline: "Ledger Reviews Its Own Reporting On Bridge Closure",
    byline: "by the Editorial Desk",
    dateline: "ROSEWOOD — MONDAY",
    body: [
      "A March story reported the Vine Street bridge would close for ~h1{eight weeks of structural repair}, a figure the county later revised to twelve.",
      "~h2{The paper issued a correction the same week}, filed in the corrections column on March 22.",
      "~h3{Editors knew the number was wrong before publishing.} No email, memo, or witness has been produced to support that.",
      "The county engineer ~h4{confirmed the revised twelve-week schedule in writing} on March 20.",
    ],
  },
  social: {
    app: "CHATTR",
    handle: "@inkspill_rw",
    display: "Ink Spill",
    avatar: "bust2",
    time: "1d",
    body: "The Ledger ~h5{buried a correction so deep it never ran}. Classic. ~h6{Their bridge story was off by four weeks.}",
    likes: "1.5K",
    reposts: "377",
    replies: "290",
  },
  quote: {
    speaker: "H. Barrow",
    role: "County Engineer",
    avatar: "bust1",
    outletNote: "Written statement, Mar 20",
    body: '"~h7{The schedule moved from eight to twelve weeks once we opened the deck.} The paper was told the day we knew."',
  },
  hotspots: [
    {
      id: "h1",
      text: "eight weeks of structural repair",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "fabricated", "exaggerate"],
      note: "Accurate as of publication — the county's own figure at the time.",
    },
    {
      id: "h2",
      text: "The paper issued a correction the same week",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "nosource", "context"],
      note: "The corrections column is dated and public. Verifiable in thirty seconds.",
    },
    {
      id: "h3",
      text: "Editors knew the number was wrong before publishing.",
      source: "article",
      misleading: true,
      correctReason: "nosource",
      chips: ["nosource", "cherry", "records"],
      note: "A claim about intent with nothing behind it. The article even admits no document exists.",
    },
    {
      id: "h4",
      text: "confirmed the revised twelve-week schedule in writing",
      source: "article",
      misleading: false,
      correctReason: "confirmed",
      chips: ["confirmed", "nosource", "exaggerate"],
      note: "In writing, dated, from the responsible engineer.",
    },
    {
      id: "h5",
      text: "buried a correction so deep it never ran",
      source: "social",
      misleading: true,
      correctReason: "fabricated",
      chips: ["fabricated", "context", "records"],
      note: "It ran, on March 22. A correction you didn't look for isn't a correction that didn't happen.",
    },
    {
      id: "h6",
      text: "Their bridge story was off by four weeks.",
      source: "social",
      misleading: false,
      correctReason: "records",
      chips: ["records", "exaggerate", "cherry"],
      note: "Eight to twelve is four. Hostile account, correct arithmetic.",
    },
    {
      id: "h7",
      text: "The schedule moved from eight to twelve weeks once we opened the deck.",
      source: "quote",
      misleading: false,
      correctReason: "onrecord",
      chips: ["onrecord", "context", "nosource"],
      note: "Named engineer, written statement, dated. Clean.",
    },
  ],
};
