import type { CaseDef } from "../../game/cases";

export const bakeryCase: CaseDef = {
  id: "bakery",
  building: "Rosewood Bakery",
  sprite: "bakery",
  spriteScale: 3,
  title: "The Rat In The Flour",
  tag: "CASE 08",
  brief: "A viral post says the neighbourhood bakery is a health hazard. Is it?",
  article: {
    outlet: "THE ROSEWOOD LEDGER",
    headline: "Beloved Bakery Under Fire After Inspection",
    byline: "by M. Alvarez",
    dateline: "ROSEWOOD — TUESDAY",
    body: [
      "Rosewood Bakery, a fixture on Fourth Street for nineteen years, ~h1{failed its city health inspection last month}, according to a report filed with the Rosewood Health Department on March 12.",
      "The inspection recorded three violations, all of them ~h2{classified by the department as minor and correctable}. Owner Dana Okonjo said the issues were fixed within a week.",
      "~h3{Locals say the place has been filthy for years.} Several customers interviewed outside the shop on Monday said they had never noticed a problem.",
      "The department confirmed the bakery ~h4{passed a follow-up inspection on March 19} and remains open with no restrictions on operation.",
    ],
  },
  social: {
    app: "CHATTR",
    handle: "@rosewood_watch",
    display: "Rosewood Watch",
    avatar: "bust1",
    time: "2h",
    body: "BREAKING: Rosewood Bakery ~h5{shut down by the health department} after inspectors found ~h6{a rat infestation in the flour store}. Nineteen years of this. Share before they delete it.",
    likes: "4.1K",
    reposts: "912",
    replies: "308",
  },
  quote: {
    speaker: "Insp. Ruth Camden",
    role: "Rosewood Health Dept.",
    avatar: "bust2",
    outletNote: "On the record, phone, Tues 4:10pm",
    body: '"We logged three minor violations and ~h7{the bakery corrected all of them before our follow-up}. There was no closure order and no evidence of pests."',
  },
  hotspots: [
    {
      id: "h1",
      text: "failed its city health inspection last month",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "nosource", "exaggerate"],
      note: "True and documented — the filed report backs it. A fact you dislike is still a fact.",
    },
    {
      id: "h2",
      text: "classified by the department as minor and correctable",
      source: "article",
      misleading: false,
      correctReason: "records",
      chips: ["records", "context", "cherry"],
      note: "Straight from the inspection report's own classification.",
    },
    {
      id: "h3",
      text: "Locals say the place has been filthy for years.",
      source: "article",
      misleading: true,
      correctReason: "nosource",
      chips: ["nosource", "records", "fabricated"],
      note: "\"Locals say\" with no local named. Anonymous crowd-voice is the oldest trick in the trade.",
    },
    {
      id: "h4",
      text: "passed a follow-up inspection on March 19",
      source: "article",
      misleading: false,
      correctReason: "confirmed",
      chips: ["confirmed", "nosource", "exaggerate"],
      note: "Confirmed by the department directly. Good sourcing.",
    },
    {
      id: "h5",
      text: "shut down by the health department",
      source: "social",
      misleading: true,
      correctReason: "exaggerate",
      chips: ["exaggerate", "context", "records"],
      note: "Three minor violations became a shutdown. That's not reporting, that's inflation.",
    },
    {
      id: "h6",
      text: "a rat infestation in the flour store",
      source: "social",
      misleading: true,
      correctReason: "fabricated",
      chips: ["fabricated", "cherry", "nosource"],
      note: "Invented whole. The inspector found no evidence of pests, and no report mentions one.",
    },
    {
      id: "h7",
      text: "the bakery corrected all of them before our follow-up",
      source: "quote",
      misleading: false,
      correctReason: "onrecord",
      chips: ["onrecord", "nosource", "context"],
      note: "Named official, on the record, with a timestamp. This is what a clean source looks like.",
    },
  ],
};
