// AUTO-GENERATED by scripts/gen-sprites.mjs — do not edit by hand.
//
// Every pixel-art sprite is a real PNG image under src/assets/<category>/.
// To add or replace a sprite: drop a PNG in the right folder and add one line
// to SPRITE_ASSETS below (plus, optionally, to the ASSETS tree). No pixel data
// lives in TypeScript anymore.

import spr_coin from "./objects/coin.png";
import spr_lock from "./objects/lock.png";
import spr_pin from "./objects/pin.png";
import spr_magnifier from "./objects/magnifier.png";
import spr_briefcase from "./objects/briefcase.png";
import spr_gear from "./objects/gear.png";
import spr_doc from "./objects/doc.png";
import spr_phone from "./objects/phone.png";
import spr_quotecard from "./objects/quotecard.png";
import spr_bronze from "./objects/bronze.png";
import spr_silver from "./objects/silver.png";
import spr_gold from "./objects/gold.png";
import spr_flag from "./ui/flag.png";
import spr_check from "./ui/check.png";
import spr_cross from "./ui/cross.png";
import spr_coffee from "./objects/coffee.png";
import spr_redpen from "./objects/redpen.png";
import spr_stamp from "./objects/stamp.png";
import spr_badge from "./ui/badge.png";
import spr_kid from "./characters/kid.png";
import spr_editor from "./characters/editor.png";
import spr_editor_1 from "./characters/editor1.png";
import spr_bust1 from "./characters/bust1.png";
import spr_bust2 from "./characters/bust2.png";
import spr_typewriter from "./objects/typewriter.png";
import spr_bakery from "./locations/bakery.png";
import spr_cityhall from "./locations/cityhall.png";
import spr_market from "./locations/market.png";
import spr_newsoffice from "./locations/newsoffice.png";
import spr_police from "./locations/police.png";
import spr_school from "./locations/school.png";
import spr_secondsource from "./objects/secondsource.png";
import spr_hourglass from "./objects/hourglass.png";
import spr_notebook from "./objects/notebook.png";
import spr_tornlogo from "./objects/tornlogo.png";
import spr_tree1 from "./locations/tree1.png";
import spr_tree2 from "./locations/tree2.png";
import spr_tree3 from "./locations/tree3.png";
import spr_hedge from "./locations/hedge.png";
import spr_lamppostOn from "./locations/lamppostOn.png";
import spr_lamppostOn_v0 from "./locations/lamppostOn__w2A3138.png";
import spr_lamppostOff from "./locations/lamppostOff.png";
import spr_bench from "./locations/bench.png";
import spr_fountain from "./locations/fountain.png";
import spr_fountain_v0 from "./locations/fountain__w2A3138.png";
import spr_bicycle from "./locations/bicycle.png";
import spr_mailbox from "./locations/mailbox.png";
import spr_mailbox_v0 from "./locations/mailbox__w2A3138.png";
import spr_busstop from "./locations/busstop.png";
import spr_birdwire from "./locations/birdwire.png";
import spr_noticeboard from "./locations/noticeboard.png";
import spr_house1 from "./locations/house1.png";
import spr_house1_v0 from "./locations/house1__w2A3138.png";
import spr_house2 from "./locations/house2.png";
import spr_house2_v0 from "./locations/house2__w2A3138.png";
import spr_house3 from "./locations/house3.png";
import spr_house3_v0 from "./locations/house3__w2A3138.png";
import spr_npcA1 from "./characters/npcA1.png";
import spr_npcA2 from "./characters/npcA2.png";
import spr_npcA3 from "./characters/npcA3.png";
import spr_npcA4 from "./characters/npcA4.png";
import spr_npcB1 from "./characters/npcB1.png";
import spr_npcB2 from "./characters/npcB2.png";
import spr_npcB3 from "./characters/npcB3.png";
import spr_npcB4 from "./characters/npcB4.png";
import spr_npcC1 from "./characters/npcC1.png";
import spr_npcC2 from "./characters/npcC2.png";
import spr_news1 from "./locations/news1.png";
import spr_news2 from "./locations/news2.png";
import spr_news3 from "./locations/news3.png";
import spr_news4 from "./locations/news4.png";
import spr_clock1 from "./objects/clock1.png";
import spr_clock2 from "./objects/clock2.png";
import spr_stopwatch from "./objects/stopwatch.png";
import spr_medal from "./objects/medal.png";
import spr_starOn from "./ui/starOn.png";
import spr_starOff from "./ui/starOff.png";
import spr_arrowR from "./ui/arrowR.png";
import spr_rumor1 from "./characters/rumor1.png";
import spr_rumor2 from "./characters/rumor2.png";
import spr_rumorIcon from "./characters/rumorIcon.png";
import spr_siftStop from "./ui/siftStop.png";
import spr_siftSource from "./ui/siftSource.png";
import spr_siftCoverage from "./ui/siftCoverage.png";
import spr_siftTrace from "./ui/siftTrace.png";
import spr_compSource from "./ui/compSource.png";
import spr_compBias from "./ui/compBias.png";
import spr_compChain from "./ui/compChain.png";
import spr_compCompare from "./ui/compCompare.png";
import spr_compGenre from "./ui/compGenre.png";
import spr_gauge from "./ui/gauge.png";
import spr_chart from "./ui/chart.png";
import spr_globe from "./ui/globe.png";
import spr_people from "./characters/people.png";
import spr_handbook from "./ui/handbook.png";
import spr_shield from "./ui/shield.png";
import spr_export from "./ui/export.png";
import spr_keyboard from "./ui/keyboard.png";
import spr_eye from "./ui/eye.png";
import spr_flagEN from "./ui/flagEN.png";
import spr_flagES from "./ui/flagES.png";
import spr_flagFR from "./ui/flagFR.png";
import spr_flagZH from "./ui/flagZH.png";
import spr_flagAR from "./ui/flagAR.png";
import spr_logoLedger from "./ui/logoLedger.png";
import spr_logoSocial from "./ui/logoSocial.png";
import spr_logoSeal from "./ui/logoSeal.png";
import spr_postoffice from "./locations/postoffice.png";
import spr_library from "./locations/library.png";
import spr_envelope from "./objects/envelope.png";
import spr_envelopeFlag from "./objects/envelopeFlag.png";
import spr_shredder from "./objects/shredder.png";
import spr_blocksign from "./objects/blocksign.png";
import spr_keycap from "./objects/keycap.png";
import spr_padlockOpen from "./objects/padlockOpen.png";
import spr_heart from "./objects/heart.png";
import spr_heartOff from "./objects/heartOff.png";
import spr_swipeLeft from "./objects/swipeLeft.png";
import spr_swipeRight from "./objects/swipeRight.png";
import spr_inbox from "./objects/inbox.png";
import spr_vault from "./objects/vault.png";
import spr_padlockShut from "./objects/padlockShut.png";
import spr_snoop from "./objects/snoop.png";
import spr_shieldDown from "./objects/shieldDown.png";
import spr_speech from "./objects/speech.png";
import spr_phoneUp from "./objects/phoneUp.png";
import spr_otp from "./objects/otp.png";
import spr_hand from "./objects/hand.png";
import spr_handSlap from "./objects/handSlap.png";
import spr_popup from "./objects/popup.png";

export type SpriteAsset = {
  /** imported PNG url (nearest-neighbour scaled at render time) */
  src: string;
  /** native pixel width / height (one grid cell = one pixel) */
  w: number;
  h: number;
  /** optional pre-baked colour variants, keyed by recolor signature */
  variants?: Record<string, string>;
};

/** Flat, name-keyed lookup used by <PixelSprite name="..." />. */
export const SPRITE_ASSETS: Record<string, SpriteAsset> = {
  "coin": { src: spr_coin, w: 12, h: 12 },
  "lock": { src: spr_lock, w: 12, h: 12 },
  "pin": { src: spr_pin, w: 12, h: 11 },
  "magnifier": { src: spr_magnifier, w: 12, h: 12 },
  "briefcase": { src: spr_briefcase, w: 12, h: 10 },
  "gear": { src: spr_gear, w: 12, h: 10 },
  "doc": { src: spr_doc, w: 12, h: 11 },
  "phone": { src: spr_phone, w: 12, h: 10 },
  "quotecard": { src: spr_quotecard, w: 12, h: 11 },
  "flag": { src: spr_flag, w: 12, h: 11 },
  "check": { src: spr_check, w: 12, h: 9 },
  "cross": { src: spr_cross, w: 12, h: 10 },
  "coffee": { src: spr_coffee, w: 12, h: 8 },
  "redpen": { src: spr_redpen, w: 12, h: 10 },
  "stamp": { src: spr_stamp, w: 16, h: 11 },
  "badge": { src: spr_badge, w: 16, h: 16 },
  "kid": { src: spr_kid, w: 20, h: 21 },
  "editor": { src: spr_editor, w: 20, h: 21 },
  "editor1": { src: spr_editor_1, w: 20, h: 21 },
  "bust1": { src: spr_bust1, w: 14, h: 12 },
  "bust2": { src: spr_bust2, w: 14, h: 12 },
  "typewriter": { src: spr_typewriter, w: 26, h: 14 },
  "bakery": { src: spr_bakery, w: 28, h: 19 },
  "cityhall": { src: spr_cityhall, w: 28, h: 20 },
  "market": { src: spr_market, w: 28, h: 17 },
  "newsoffice": { src: spr_newsoffice, w: 28, h: 19 },
  "police": { src: spr_police, w: 28, h: 19 },
  "school": { src: spr_school, w: 28, h: 20 },
  "secondsource": { src: spr_secondsource, w: 12, h: 10 },
  "hourglass": { src: spr_hourglass, w: 12, h: 10 },
  "notebook": { src: spr_notebook, w: 12, h: 10 },
  "tornlogo": { src: spr_tornlogo, w: 16, h: 5 },
  "tree1": { src: spr_tree1, w: 12, h: 16 },
  "tree2": { src: spr_tree2, w: 12, h: 14 },
  "tree3": { src: spr_tree3, w: 8, h: 8 },
  "hedge": { src: spr_hedge, w: 16, h: 6 },
  "lamppostOn": { src: spr_lamppostOn, w: 8, h: 16, variants: { "w:#2A3138": spr_lamppostOn_v0 } },
  "lamppostOff": { src: spr_lamppostOff, w: 8, h: 16 },
  "bench": { src: spr_bench, w: 14, h: 9 },
  "fountain": { src: spr_fountain, w: 20, h: 14, variants: { "w:#2A3138": spr_fountain_v0 } },
  "bicycle": { src: spr_bicycle, w: 14, h: 9 },
  "mailbox": { src: spr_mailbox, w: 8, h: 10, variants: { "w:#2A3138": spr_mailbox_v0 } },
  "busstop": { src: spr_busstop, w: 16, h: 10 },
  "birdwire": { src: spr_birdwire, w: 24, h: 5 },
  "noticeboard": { src: spr_noticeboard, w: 14, h: 13 },
  "house1": { src: spr_house1, w: 16, h: 13, variants: { "w:#2A3138": spr_house1_v0 } },
  "house2": { src: spr_house2, w: 16, h: 14, variants: { "w:#2A3138": spr_house2_v0 } },
  "house3": { src: spr_house3, w: 16, h: 11, variants: { "w:#2A3138": spr_house3_v0 } },
  "npcA1": { src: spr_npcA1, w: 8, h: 12 },
  "npcA2": { src: spr_npcA2, w: 8, h: 12 },
  "npcA3": { src: spr_npcA3, w: 8, h: 12 },
  "npcA4": { src: spr_npcA4, w: 8, h: 12 },
  "npcB1": { src: spr_npcB1, w: 8, h: 12 },
  "npcB2": { src: spr_npcB2, w: 8, h: 12 },
  "npcB3": { src: spr_npcB3, w: 8, h: 12 },
  "npcB4": { src: spr_npcB4, w: 8, h: 12 },
  "npcC1": { src: spr_npcC1, w: 8, h: 12 },
  "npcC2": { src: spr_npcC2, w: 8, h: 12 },
  "news1": { src: spr_news1, w: 8, h: 6 },
  "news2": { src: spr_news2, w: 8, h: 6 },
  "news3": { src: spr_news3, w: 8, h: 6 },
  "news4": { src: spr_news4, w: 8, h: 6 },
  "clock1": { src: spr_clock1, w: 10, h: 10 },
  "clock2": { src: spr_clock2, w: 10, h: 10 },
  "stopwatch": { src: spr_stopwatch, w: 10, h: 10 },
  "medal": { src: spr_medal, w: 10, h: 10 },
  "bronze": { src: spr_bronze, w: 16, h: 16 },
  "silver": { src: spr_silver, w: 16, h: 16 },
  "gold": { src: spr_gold, w: 16, h: 16 },
  "starOn": { src: spr_starOn, w: 9, h: 9 },
  "starOff": { src: spr_starOff, w: 9, h: 9 },
  "arrowR": { src: spr_arrowR, w: 7, h: 9 },
  "rumor1": { src: spr_rumor1, w: 18, h: 20 },
  "rumor2": { src: spr_rumor2, w: 18, h: 20 },
  "rumorIcon": { src: spr_rumorIcon, w: 18, h: 20 },
  "siftStop": { src: spr_siftStop, w: 12, h: 10 },
  "siftSource": { src: spr_siftSource, w: 12, h: 11 },
  "siftCoverage": { src: spr_siftCoverage, w: 12, h: 10 },
  "siftTrace": { src: spr_siftTrace, w: 12, h: 7 },
  "compSource": { src: spr_compSource, w: 12, h: 12 },
  "compBias": { src: spr_compBias, w: 12, h: 9 },
  "compChain": { src: spr_compChain, w: 12, h: 8 },
  "compCompare": { src: spr_compCompare, w: 12, h: 7 },
  "compGenre": { src: spr_compGenre, w: 12, h: 8 },
  "gauge": { src: spr_gauge, w: 12, h: 8 },
  "chart": { src: spr_chart, w: 12, h: 9 },
  "globe": { src: spr_globe, w: 12, h: 10 },
  "people": { src: spr_people, w: 12, h: 8 },
  "handbook": { src: spr_handbook, w: 12, h: 9 },
  "shield": { src: spr_shield, w: 12, h: 10 },
  "export": { src: spr_export, w: 10, h: 10 },
  "keyboard": { src: spr_keyboard, w: 12, h: 7 },
  "eye": { src: spr_eye, w: 12, h: 7 },
  "flagEN": { src: spr_flagEN, w: 12, h: 8 },
  "flagES": { src: spr_flagES, w: 12, h: 8 },
  "flagFR": { src: spr_flagFR, w: 12, h: 8 },
  "flagZH": { src: spr_flagZH, w: 12, h: 8 },
  "flagAR": { src: spr_flagAR, w: 12, h: 8 },
  "logoLedger": { src: spr_logoLedger, w: 16, h: 12 },
  "logoSocial": { src: spr_logoSocial, w: 16, h: 10 },
  "logoSeal": { src: spr_logoSeal, w: 16, h: 11 },
  "postoffice": { src: spr_postoffice, w: 28, h: 20 },
  "library": { src: spr_library, w: 28, h: 20 },
  "envelope": { src: spr_envelope, w: 12, h: 8 },
  "envelopeFlag": { src: spr_envelopeFlag, w: 12, h: 8 },
  "shredder": { src: spr_shredder, w: 14, h: 10 },
  "blocksign": { src: spr_blocksign, w: 12, h: 10 },
  "keycap": { src: spr_keycap, w: 12, h: 9 },
  "padlockOpen": { src: spr_padlockOpen, w: 12, h: 10 },
  "heart": { src: spr_heart, w: 10, h: 8 },
  "heartOff": { src: spr_heartOff, w: 10, h: 8 },
  "swipeLeft": { src: spr_swipeLeft, w: 12, h: 7 },
  "swipeRight": { src: spr_swipeRight, w: 12, h: 7 },
  "inbox": { src: spr_inbox, w: 14, h: 9 },
  "vault": { src: spr_vault, w: 14, h: 11 },
  "padlockShut": { src: spr_padlockShut, w: 12, h: 10 },
  "snoop": { src: spr_snoop, w: 12, h: 10 },
  "shieldDown": { src: spr_shieldDown, w: 12, h: 10 },
  "speech": { src: spr_speech, w: 12, h: 9 },
  "phoneUp": { src: spr_phoneUp, w: 12, h: 10 },
  "otp": { src: spr_otp, w: 14, h: 8 },
  "hand": { src: spr_hand, w: 12, h: 9 },
  "handSlap": { src: spr_handSlap, w: 12, h: 9 },
  "popup": { src: spr_popup, w: 12, h: 8 },
};

/**
 * Semantic asset tree. Reference assets by meaning, e.g.
 *   ASSETS.objects.coin
 *   ASSETS.characters.editor
 *
 * Characters can hold multiple expressions/variations without duplicating
 * logic. Drop the images in assets/characters/<name>/ and list them here:
 *
 *   characters: {
 *     margaretOdell: {
 *       neutral, concerned, surprised, suspicious, happy, angry,
 *     },
 *   }
 */
export const ASSETS = {
  characters: {
    "kid": spr_kid,
    "editor": spr_editor,
    "editor1": spr_editor_1,
    "bust1": spr_bust1,
    "bust2": spr_bust2,
    "npcA1": spr_npcA1,
    "npcA2": spr_npcA2,
    "npcA3": spr_npcA3,
    "npcA4": spr_npcA4,
    "npcB1": spr_npcB1,
    "npcB2": spr_npcB2,
    "npcB3": spr_npcB3,
    "npcB4": spr_npcB4,
    "npcC1": spr_npcC1,
    "npcC2": spr_npcC2,
    "rumor1": spr_rumor1,
    "rumor2": spr_rumor2,
    "rumorIcon": spr_rumorIcon,
    "people": spr_people,
  },
  objects: {
    "coin": spr_coin,
    "lock": spr_lock,
    "pin": spr_pin,
    "magnifier": spr_magnifier,
    "briefcase": spr_briefcase,
    "gear": spr_gear,
    "doc": spr_doc,
    "phone": spr_phone,
    "quotecard": spr_quotecard,
    "coffee": spr_coffee,
    "redpen": spr_redpen,
    "stamp": spr_stamp,
    "typewriter": spr_typewriter,
    "secondsource": spr_secondsource,
    "hourglass": spr_hourglass,
    "notebook": spr_notebook,
    "tornlogo": spr_tornlogo,
    "clock1": spr_clock1,
    "clock2": spr_clock2,
    "stopwatch": spr_stopwatch,
    "medal": spr_medal,
    "envelope": spr_envelope,
    "envelopeFlag": spr_envelopeFlag,
    "shredder": spr_shredder,
    "blocksign": spr_blocksign,
    "keycap": spr_keycap,
    "padlockOpen": spr_padlockOpen,
    "heart": spr_heart,
    "heartOff": spr_heartOff,
    "swipeLeft": spr_swipeLeft,
    "swipeRight": spr_swipeRight,
    "inbox": spr_inbox,
    "vault": spr_vault,
    "padlockShut": spr_padlockShut,
    "snoop": spr_snoop,
    "shieldDown": spr_shieldDown,
    "speech": spr_speech,
    "phoneUp": spr_phoneUp,
    "otp": spr_otp,
    "hand": spr_hand,
    "handSlap": spr_handSlap,
    "popup": spr_popup,
  },
  locations: {
    "bakery": spr_bakery,
    "cityhall": spr_cityhall,
    "market": spr_market,
    "newsoffice": spr_newsoffice,
    "police": spr_police,
    "school": spr_school,
    "tree1": spr_tree1,
    "tree2": spr_tree2,
    "tree3": spr_tree3,
    "hedge": spr_hedge,
    "lamppostOn": spr_lamppostOn,
    "lamppostOff": spr_lamppostOff,
    "bench": spr_bench,
    "fountain": spr_fountain,
    "bicycle": spr_bicycle,
    "mailbox": spr_mailbox,
    "busstop": spr_busstop,
    "birdwire": spr_birdwire,
    "noticeboard": spr_noticeboard,
    "house1": spr_house1,
    "house2": spr_house2,
    "house3": spr_house3,
    "news1": spr_news1,
    "news2": spr_news2,
    "news3": spr_news3,
    "news4": spr_news4,
    "postoffice": spr_postoffice,
    "library": spr_library,
  },
  ui: {
    "flag": spr_flag,
    "check": spr_check,
    "cross": spr_cross,
    "badge": spr_badge,
    "starOn": spr_starOn,
    "starOff": spr_starOff,
    "arrowR": spr_arrowR,
    "siftStop": spr_siftStop,
    "siftSource": spr_siftSource,
    "siftCoverage": spr_siftCoverage,
    "siftTrace": spr_siftTrace,
    "compSource": spr_compSource,
    "compBias": spr_compBias,
    "compChain": spr_compChain,
    "compCompare": spr_compCompare,
    "compGenre": spr_compGenre,
    "gauge": spr_gauge,
    "chart": spr_chart,
    "globe": spr_globe,
    "handbook": spr_handbook,
    "shield": spr_shield,
    "export": spr_export,
    "keyboard": spr_keyboard,
    "eye": spr_eye,
    "flagEN": spr_flagEN,
    "flagES": spr_flagES,
    "flagFR": spr_flagFR,
    "flagZH": spr_flagZH,
    "flagAR": spr_flagAR,
    "logoLedger": spr_logoLedger,
    "logoSocial": spr_logoSocial,
    "logoSeal": spr_logoSeal,
  },
} as const;
